name: Deploy FE to VPS

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            --build-arg VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }} \
            -t ecommerce-fe .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ecommerce-fe ${{ secrets.DOCKER_USERNAME }}/ecommerce-fe:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-fe:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo ">>> Pulling latest Docker image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-fe:latest
            
            echo ">>> Stopping & removing old container"
            docker stop ecommerce-fe || true
            docker rm ecommerce-fe || true
            
            echo ">>> Running new container"
            docker run -d \
              --name ecommerce-fe \
              --env-file /home/jackie/ENV/ecommerce-fe/.env \
              -p 5173:80 \
              ${{ secrets.DOCKER_USERNAME }}/ecommerce-fe:latest

# deploy